version: "3.8"

services:
  postgres:
    image: postgres
    container_name: meu-postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
